# Generated by Django 5.1.6 on 2025-04-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_services", "0002_populate_wallet_field"),
    ]

    operations = []
