"""
Django settings for sacco_managment project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_xw^7ywak0*p2gyt4&5@27)-^(p(2c8n9b=l*6p4rup6iih4dv"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    
    # My Apps
    "core",
    "user_auths",
    "account",
    "financial_services",
    "reports",
    "support",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_user_agents.middleware.UserAgentMiddleware",
]


# User agent
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

USER_AGENTS_CACHE = 'default'



ROOT_URLCONF = "sacco_managment.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sacco_managment.wsgi.application"




# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"


STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



AUTH_USER_MODEL = "user_auths.User"



JAZZMIN_SETTINGS = {
    # General Settings
    "site_title": "SACCO Admin Pro",
    "site_header": "Prime SACCO Management",
    "site_brand": "Prime SACCO",
    "site_logo": "assets/imgs/logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "img/favicon.ico",
    "welcome_sign": "Welcome to Prime SACCO Administration Portal",
    "copyright": "Prime SACCO Ltd ",

    # Theme Settings
    "theme": "flatly",
    "dark_mode_theme": "cyborg",
    "show_ui_builder": True,

    # Custom Icons & Styling
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users",
        "sacco.Member": "fas fa-user-tie",
        "sacco.Account": "fas fa-wallet",
        "sacco.Transaction": "fas fa-money-check-alt",
        "sacco.Loan": "fas fa-hand-holding-usd",
        "sacco.Branch": "fas fa-university",
        "admin.LogEntry": "fas fa-file",
        "user_auths.User": "fas fa-user",
        "user_auths.Profile": "fas fa-address-card",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-dot-circle",

    # Top Menu Configuration
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Public Site", "url": "/", "new_window": True},
        {"app": "sacco"},
        {"model": "sacco.Member"},
        {"model": "sacco.Transaction"},
        {"name": "Support", "url": "https://support.primesacco.com", "new_window": True},
    ],

    # Sidebar Customization
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "sacco",
        "sacco.Member", 
        "sacco.Account",
        "sacco.Transaction",
        "sacco.Loan",
        "auth",
        "store",
        "store.product",
        "store.cartorder",
        "store.cartorderitem",
        "store.category",
        "store.brand",
        "store.productfaq",
        "store.productoffers",
        "store.productbidders",
        "store.review",
        "vendor",
        "user_auths",
        "addons",
        "addons.Company",
        "addons.BasicAddon",
    ],
    
    "custom_links": {
        "sacco": [{
            "name": "Financial Reports", 
            "url": "financial_reports",
            "icon": "fas fa-chart-line",
            "permissions": ["sacco.view_transaction"]
        }]
    },

    # Advanced UI Configuration
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "sacco.Transaction": "single",
    },
    "related_modal_active": True,
    "use_google_fonts_cdn": True,

    # Custom CSS/JS
    "custom_css": "css/admin-custom.css",
    "custom_js": "js/admin-custom.js",

    # Additional Features
    # "search_model": ["sacco.Member", "sacco.Account", "auth.User"],
    "language_chooser": False,
    "user_avatar": "avatar",
}

# JAZZMIN_UI_TWEAKS = {
#     "navbar_small_text": False,
#     "footer_small_text": False,
#     "body_small_text": False,  # Set to False for better readability
#     "brand_small_text": False,
#     "brand_colour": "navbar-primary",  # Improved color consistency
#     "accent": "accent-lightblue",  # A more modern accent color
#     "navbar": "navbar-primary navbar-dark",
#     "no_navbar_border": True,  # Cleaner look without the navbar border
#     "navbar_fixed": True,  # Keep navbar fixed for easier navigation
#     "layout_boxed": False,
#     "footer_fixed": False,
#     "sidebar_fixed": True,  # Fix sidebar for better UX
#     "sidebar": "sidebar-dark-primary",  # Darker sidebar for contrast
#     "sidebar_nav_small_text": False,
#     "sidebar_disable_expand": False,
#     "sidebar_nav_child_indent": True,  # Better structure for nested items
#     "sidebar_nav_compact_style": True,  # Compact menu for better navigation
#     "sidebar_nav_legacy_style": False,
#     "sidebar_nav_flat_style": True,  # Flat style for a modern look
#     "theme": "lux",  # More refined UI theme
#     "dark_mode_theme": "darkly",  # A more visually appealing dark mode
#     "button_classes": {
#         "primary": "btn-primary",
#         "secondary": "btn-outline-secondary",
#         "info": "btn-outline-info",
#         "warning": "btn-outline-warning",
#         "danger": "btn-outline-danger",
#         "success": "btn-outline-success",
#     },
# }


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,  # Better readability
    "brand_small_text": False,
    "brand_colour": "navbar-dark",  # Dark navbar for a professional look
    "accent": "accent-gold",  # Gold accent for premium feel
    "navbar": "navbar-dark navbar-navy",  # Navy blue navbar for a corporate look
    "no_navbar_border": True,  # Cleaner look
    "navbar_fixed": True,  # Keep navbar fixed for easy navigation
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,  # Fixed sidebar for easy access to menu items
    "sidebar": "sidebar-dark-primary",  # Dark sidebar for contrast
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,  # More structured sidebar
    "sidebar_nav_compact_style": True,  # Clean and modern compact style
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,  # Flat UI for modern look
    "theme": "superhero",  # Premium banking UI feel
    "dark_mode_theme": "solar",  # Optimized dark mode for finance/admin users
    "button_classes": {
        "primary": "btn-primary btn-lg",  # Larger buttons for easier interaction
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
}
