# Generated by Django 5.1.6 on 2025-05-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="identity_type",
            field=models.CharField(
                choices=[
                    ("national_id_card", "National ID Card"),
                    ("Refugee_id_card", "Refugee ID Card"),
                    ("drivers_licence", "Drives Licence"),
                    ("international_passport", "International Passport"),
                ],
                max_length=140,
            ),
        ),
    ]
