# Generated by Django 5.1.6 on 2025-06-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_kyc_identity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="locked_funds",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="account",
            name="mobile_money_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
