# Generated by Django 5.1.6 on 2025-06-22 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPPORT", "Support Staff"),
                            ("LOAN_OFFICER", "Loan Officer"),
                            ("ACCOUNT_MANAGER", "Account Manager"),
                            ("ADMIN", "System Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("can_view_balances", models.BooleanField(default=False)),
                ("can_reset_passwords", models.BooleanField(default=False)),
                ("can_approve_loans", models.BooleanField(default=False)),
                ("can_edit_kyc", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
