# Generated by Django 5.1.6 on 2025-06-24 07:02

import django.db.models.deletion
import shortuuid.django_fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_staffpermission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="kyc",
            options={"ordering": ["-date_created"]},
        ),
        migrations.RenameField(
            model_name="account",
            old_name="date",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="kyc",
            old_name="date",
            new_name="date_created",
        ),
        migrations.AlterField(
            model_name="account",
            name="account_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                length=7,
                max_length=10,
                prefix="DEX",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                length=10,
                max_length=13,
                prefix="217",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("in-active", "Inactive"),
                ],
                default="in-active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="pin_number",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890", length=4, max_length=4, prefix="", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="recommended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommended_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="red_code",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh1234567890",
                length=10,
                max_length=10,
                prefix="",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="fax",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="identity_type",
            field=models.CharField(
                choices=[
                    ("national_id_card", "National ID Card"),
                    ("refugee_id_card", "Refugee ID Card"),
                    ("drivers_license", "Driver’s License"),
                    ("international_passport", "International Passport"),
                ],
                max_length=140,
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="mobile",
            field=models.CharField(max_length=100),
        ),
    ]
