# Generated by Django 5.1.6 on 2025-06-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_account_options_alter_auditlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kyc",
            name="kyc_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
