# Generated by Django 5.1.6 on 2025-02-16 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialreport",
            options={
                "ordering": ["-generated_at"],
                "verbose_name": "Financial Report",
                "verbose_name_plural": "Financial Reports",
            },
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="reports/"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("TRANSACTION", "Transaction Report"),
                    ("SUMMARY", "Financial Summary"),
                ],
                default="TRANSACTION",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="transactions",
            field=models.ManyToManyField(related_name="reports", to="core.transaction"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
