# Generated by Django 5.1.6 on 2025-06-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("MEMBER", "Member"),
                    ("STAFF", "Staff"),
                    ("ADMIN", "Admin"),
                    ("SUPER_ADMIN", "Super Admin"),
                ],
                default="MEMBER",
                max_length=20,
            ),
        ),
    ]
