# Generated by Django 5.1.6 on 2025-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_loanapplication_loanrepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
