# Generated by Django 5.1.6 on 2025-06-18 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_account_locked_funds_account_mobile_money_balance"),
        ("core", "0003_notification_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="receiver_account",
        ),
        migrations.AddField(
            model_name="transaction",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="receiver_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receiver_account",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transfer"),
                    ("received", "Received"),
                    ("withdraw", "withdraw"),
                    ("deposit", "Deposit"),
                    ("loan_disbursement", "Loan Disbursement"),
                    ("refund", "Refund"),
                    ("request", "Payment Request"),
                    ("mobile_money_deposit", "Mobile Money Deposit"),
                    ("mobile_money_withdrawal", "Mobile Money Withdrawal"),
                    ("none", "None"),
                ],
                default="none",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="MobileMoneyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("MTN", "MTN"), ("Airtel", "Airtel")], max_length=20
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("transaction_ref", models.CharField(max_length=50, unique=True)),
                ("is_reconciled", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_money",
                        to="core.transaction",
                    ),
                ),
            ],
        ),
    ]
